// th.js - Thai translation dictionary.
//
// Keys are the exact canonical English strings used in the code (see
// i18n.js). Parameterized keys keep their {placeholder} tokens. Survey
// instruments follow the standard Thai wording where an official Thai
// version exists (WHO-5, ST-5 from the Thai DMH, GSE, UCLA-3, LSNS-6).
// Benchmark SOURCE labels stay in English on purpose (literature citations).

export const TH = {
  // --- Duty-of-care mental-health support (finding #4) ---
  "If things feel heavy, you don't have to face it alone": "ถ้ารู้สึกหนักใจ คุณไม่จำเป็นต้องเผชิญมันเพียงลำพัง",
  "Your recent well-being and stress answers suggest you may be going through a difficult time. This is a self-check, not a diagnosis — talking to a professional can help.": "คำตอบเรื่องสุขภาวะและความเครียดล่าสุดของคุณ บ่งชี้ว่าคุณอาจกำลังเผชิญช่วงเวลาที่ยากลำบาก นี่เป็นเพียงการประเมินตนเอง ไม่ใช่การวินิจฉัย การพูดคุยกับผู้เชี่ยวชาญสามารถช่วยได้",
  "Dept. of Mental Health hotline (free, 24 hrs)": "สายด่วนสุขภาพจิต กรมสุขภาพจิต (ฟรี ตลอด 24 ชม.)",
  "Samaritans of Thailand": "สมาคมสะมาริตันส์แห่งประเทศไทย",
  "Medical emergency": "เหตุฉุกเฉินทางการแพทย์",
  "Mental health support": "การสนับสนุนด้านสุขภาพจิต",
  // --- Instrument-fidelity disclosures (finding #8) ---
  "Grit (perseverance)": "Grit (ความเพียร)",
  "Perseverance facet only — {g}/5 vs the ~3.4 full-scale reference": "เฉพาะด้านความเพียร — {g}/5 เทียบกับค่าอ้างอิงเต็มสเกล ~3.4",
  "Raw {n}/20 — scored on a simple linear scale, not the CFPB's official score table": "คะแนนดิบ {n}/20 — คิดคะแนนแบบเชิงเส้นอย่างง่าย ไม่ใช่ตารางคะแนนทางการของ CFPB",
  "Full 10-item scale — raw {n}/40, linear scoring (not the official CFPB table)": "สเกลเต็ม 10 ข้อ — คะแนนดิบ {n}/40 คิดแบบเชิงเส้น (ไม่ใช่ตารางทางการของ CFPB)",
  "Grit {g}/5 from your full 12-item scale vs the ~3.4 adult reference point.": "Grit {g}/5 จากสเกลเต็ม 12 ข้อ เทียบกับค่าอ้างอิงผู้ใหญ่ ~3.4",
  "Grit {g}/5 — the onboarding measure is the perseverance facet only (4 of the 8 Grit-S items), so this is indicative, not an exact match to the ~3.4 reference.": "Grit {g}/5 — แบบวัดตอนเริ่มต้นครอบคลุมเฉพาะด้านความเพียร (4 จาก 8 ข้อของ Grit-S) จึงเป็นเพียงค่าชี้บ่ง ไม่ใช่การเทียบตรงกับค่าอ้างอิง ~3.4",
  // --- Core-surface i18n leaks fixed (finding #10) ---
  "Life Balance Index": "ดัชนีสมดุลชีวิต",
  "Lv.": "Lv.",
  "Points: {xp} / {needed}": "คะแนน: {xp} / {needed}",
  "S-Rank": "ระดับ S",
  "A-Rank": "ระดับ A",
  "B-Rank": "ระดับ B",
  "C-Rank": "ระดับ C",
  "D-Rank": "ระดับ D",
  // Recovery banner + storage-error toast (findings #1/#2, now translated)
  "We found earlier data we couldn't open after an update. Download it before it's replaced.": "เราพบข้อมูลเก่าที่เปิดไม่ได้หลังการอัปเดต ดาวน์โหลดเก็บไว้ก่อนที่จะถูกแทนที่",
  "Download old data": "ดาวน์โหลดข้อมูลเก่า",
  "Old data downloaded.": "ดาวน์โหลดข้อมูลเก่าแล้ว",
  "Dismiss": "ปิด",
  "Your device wouldn't save that change — storage may be full or you're in private mode. Export a backup to avoid losing progress.": "อุปกรณ์ของคุณบันทึกการเปลี่ยนแปลงนั้นไม่ได้ — พื้นที่จัดเก็บอาจเต็มหรือคุณอยู่ในโหมดส่วนตัว ส่งออกข้อมูลสำรองเพื่อไม่ให้ความคืบหน้าสูญหาย",
  // Age is collected but no benchmark norm uses it yet, so the label no
  // longer implies it does (review LOW finding).
  "Age": "อายุ",
  // --- Chart accessible names (review finding: SVGs were silent to AT) ---
  "Trend chart: {n} weekly snapshot(s), latest score {latest} of 100": "แผนภูมิแนวโน้ม: สแนปช็อตรายสัปดาห์ {n} รายการ คะแนนล่าสุด {latest} จาก 100",
  "Radar chart of the eight aspect scores: {summary}": "แผนภูมิเรดาร์คะแนนทั้งแปดด้าน: {summary}",
  // --- Footer (privacy/source/version reachable from the app) ---
  "Privacy & Data": "ความเป็นส่วนตัวและข้อมูล",
  "Source code & license": "ซอร์สโค้ดและสัญญาอนุญาต",
  "Version {v}": "เวอร์ชัน {v}",
  // --- Accessibility route announcer (finding #12) ---
  "Re-assessment": "การประเมินซ้ำ",
  "In-depth assessment": "การประเมินเชิงลึก",
  "{view} view": "หน้า {view}",
  // --- App chrome (header, tabs, dialogs) ---
  "Life Balance Index — Personal Wellbeing Assessment": "ดัชนีสมดุลชีวิต — แบบประเมินสุขภาวะส่วนบุคคล",
  "Personal Wellbeing Assessment": "แบบประเมินสุขภาวะส่วนบุคคล",
  "Export": "ส่งออก",
  "Import": "นำเข้า",
  "Reset Data": "ล้างข้อมูล",
  "Overview": "ภาพรวม",
  "Activity Log": "บันทึกกิจกรรม",
  "Goals": "เป้าหมาย",
  "Peer Comparison": "เปรียบเทียบกับผู้อื่น",
  "Are you sure you want to erase all records and your baseline assessment? This cannot be undone.":
    "แน่ใจหรือไม่ว่าต้องการลบบันทึกทั้งหมดและแบบประเมินพื้นฐานของคุณ? การกระทำนี้ย้อนกลับไม่ได้",
  "Importing a backup replaces ALL current data. Continue?": "การนำเข้าข้อมูลสำรองจะแทนที่ข้อมูลปัจจุบันทั้งหมด ดำเนินการต่อหรือไม่?",
  "Data exported.": "ส่งออกข้อมูลแล้ว",
  "Data imported successfully.": "นำเข้าข้อมูลสำเร็จ",
  "Import failed: {msg}": "นำเข้าไม่สำเร็จ: {msg}",
  "Activity recorded: +{xp} points{detail}.": "บันทึกกิจกรรมแล้ว: +{xp} คะแนน{detail}",
  "Re-assessment complete: {parts} (+40 points)": "ประเมินซ้ำเสร็จสิ้น: {parts} (+40 คะแนน)",
  "Re-assessment needs a baseline — complete the initial assessment first.": "การประเมินซ้ำต้องมีข้อมูลพื้นฐานก่อน — กรุณาทำแบบประเมินแรกให้เสร็จก่อน",
  "Level Up": "เลื่อนระดับ",
  "Your overall progress level has increased.": "ระดับความก้าวหน้าโดยรวมของคุณเพิ่มขึ้นแล้ว",
  "LEVEL {n}": "เลเวล {n}",
  "Rank: {rank}": "ระดับ: {rank}",
  "Continue": "ดำเนินการต่อ",
  'Goal completed: "{title}" (+{xp} points)': 'บรรลุเป้าหมาย: "{title}" (+{xp} คะแนน)',
  "Weekly commitment met — +{bonus} bonus points.": "ทำตามคำมั่นประจำสัปดาห์สำเร็จ — โบนัส +{bonus} คะแนน",
  "Here to help. Focus on logging your routines today to build momentum.":
    "ยินดีช่วยเหลือ วันนี้ลองโฟกัสที่การบันทึกกิจวัตรเพื่อสร้างแรงส่งดูนะ",

  // --- Proficiency tiers ---
  "Foundational": "ระดับพื้นฐาน",
  "Developing": "กำลังพัฒนา",
  "Progressing": "ก้าวหน้า",
  "Proficient": "ชำนาญ",
  "Advanced": "ขั้นสูง",
  "Distinguished": "ดีเด่น",
  "Exemplary": "เป็นแบบอย่าง",

  // --- Aspects ---
  "Finance": "การเงิน",
  "Physical": "ร่างกาย",
  "Mental": "จิตใจ",
  "Relationships": "ความสัมพันธ์",
  "Personal Goals": "เป้าหมายส่วนตัว",
  "Social Contribution": "การช่วยเหลือสังคม",
  "Environment": "สิ่งแวดล้อม",
  "Humanity's Future": "อนาคตมนุษยชาติ",
  "Income standing, financial well-being, and savings habits.": "สถานะรายได้ สุขภาวะทางการเงิน และนิสัยการออม",
  "Weekly activity, body composition, sleep, and nutrition.": "กิจกรรมรายสัปดาห์ องค์ประกอบร่างกาย การนอน และโภชนาการ",
  "Well-being (WHO-5) and stress resilience (Thai DMH ST-5).": "สุขภาวะ (WHO-5) และความทนทานต่อความเครียด (ST-5 กรมสุขภาพจิต)",
  "Social network strength, loneliness, and romantic satisfaction.": "ความแข็งแรงของเครือข่ายสังคม ความเหงา และความพึงพอใจในความรัก",
  "Self-efficacy, grit, and active learning habits.": "การรับรู้ความสามารถของตนเอง ความมุ่งมั่น และนิสัยการเรียนรู้",
  "Giving, volunteering, and prosocial habits.": "การให้ การอาสา และพฤติกรรมเพื่อสังคม",
  "Plastic footprint and everyday green behavior.": "การใช้พลาสติกและพฤติกรรมรักษ์โลกในชีวิตประจำวัน",
  "Future skills, long-term security, and future orientation.": "ทักษะแห่งอนาคต ความมั่นคงระยะยาว และการมองการณ์ไกล",

  // --- Profile values shown on the dashboard ---
  "Bangkok": "กรุงเทพฯ",
  "Provinces": "ต่างจังหวัด",
  "Office Worker": "พนักงานออฟฟิศ",
  "Freelancer": "ฟรีแลนซ์",
  "Business Owner": "เจ้าของธุรกิจ",
  "Unemployed": "ว่างงาน",
  "Single": "โสด",
  "Coupled": "มีคู่",

  // --- Onboarding ---
  "PERSONAL WELLBEING ASSESSMENT": "แบบประเมินสุขภาวะส่วนบุคคล",
  "Baseline Assessment": "แบบประเมินพื้นฐาน",
  "Step 1: Profile & Finance": "ขั้นที่ 1: ข้อมูลส่วนตัวและการเงิน",
  "Step {n} of {total}": "ขั้นที่ {n} จาก {total}",
  "About 5 minutes total": "ใช้เวลาทั้งหมดประมาณ 5 นาที",
  "You can finish here anytime": "คุณจบตรงนี้เมื่อไรก็ได้",
  "See my results now": "ดูผลลัพธ์ของฉันเลย",
  "Optional": "ไม่บังคับ",
  "We start with income and demographics so your scores can be compared against real population benchmarks.": "เราเริ่มจากรายได้และข้อมูลประชากร เพื่อให้เทียบคะแนนของคุณกับเกณฑ์มาตรฐานประชากรจริงได้",
  "A few body and activity numbers place your physical health against national norms.": "ตัวเลขร่างกายและกิจกรรมเพียงไม่กี่ข้อ ช่วยวัดสุขภาพกายของคุณเทียบกับเกณฑ์ระดับประเทศ",
  "Two validated screens (ST-5, WHO-5) estimate stress and well-being. This is a self-check, not a diagnosis.": "แบบคัดกรองที่ผ่านการรับรองสองชุด (ST-5, WHO-5) ประเมินความเครียดและสุขภาวะ นี่เป็นการตรวจสอบตนเอง ไม่ใช่การวินิจฉัย",
  "Optional — you can see your results now, or answer to score social connection and loneliness.": "ไม่บังคับ — คุณดูผลลัพธ์เลยก็ได้ หรือจะตอบเพื่อประเมินความสัมพันธ์ทางสังคมและความเหงา",
  "Optional — self-efficacy and perseverance, plus your weekly learning habits.": "ไม่บังคับ — ความเชื่อมั่นในความสามารถและความมุ่งมั่น พร้อมนิสัยการเรียนรู้รายสัปดาห์",
  "Optional — prosocial habits, everyday environmental behavior, and your long-term outlook.": "ไม่บังคับ — พฤติกรรมช่วยเหลือสังคม การดูแลสิ่งแวดล้อมในชีวิตประจำวัน และมุมมองระยะยาว",
  "Quick-start results.": "ผลลัพธ์แบบเริ่มเร็ว",
  "Aspects beyond your first sections use baseline estimates. Log routines to shape them, and monthly re-assessments refine your survey scores over time.": "ด้านที่อยู่นอกเหนือช่วงแรกใช้ค่าประมาณพื้นฐาน บันทึกกิจวัตรเพื่อปรับให้ตรงขึ้น และการประเมินซ้ำรายเดือนจะปรับคะแนนแบบสำรวจของคุณให้แม่นยำขึ้นเมื่อเวลาผ่านไป",
  "points": "คะแนน",
  "Name": "ชื่อ",
  "E.g., Alex": "เช่น อเล็กซ์",
  "Guest": "ผู้มาเยือน",
  "Age (for population benchmarks)": "อายุ (ใช้เทียบสถิติประชากร)",
  "Gender (for benchmark norms)": "เพศ (ใช้เทียบเกณฑ์มาตรฐาน)",
  "Prefer not to say": "ไม่ระบุ",
  "Male": "ชาย",
  "Female": "หญิง",
  "Primary Region (Cost of Living Mapping)": "ภูมิภาคหลัก (ใช้เทียบค่าครองชีพ)",
  "Provinces / Upcountry Thailand": "ต่างจังหวัด",
  "Bangkok & Vicinity": "กรุงเทพฯ และปริมณฑล",
  "Employment Status": "สถานะการทำงาน",
  "Office Worker / Salary Employee": "พนักงานออฟฟิศ / พนักงานประจำ",
  "Freelancer / Independent": "ฟรีแลนซ์ / อาชีพอิสระ",
  "Business Owner / Entrepreneur": "เจ้าของธุรกิจ / ผู้ประกอบการ",
  "Unemployed / Looking for Work": "ว่างงาน / กำลังหางาน",
  "Student": "นักเรียน/นักศึกษา",
  "Relationship Status": "สถานะความสัมพันธ์",
  "In a Relationship / Married": "มีแฟน / แต่งงานแล้ว",
  "Monthly Individual Income (Net THB)": "รายได้ส่วนตัวต่อเดือน (บาทสุทธิ)",
  "Monthly Savings Rate (% of Income)": "อัตราการออมต่อเดือน (% ของรายได้)",
  "Step 2: Physical Baseline": "ขั้นที่ 2: พื้นฐานร่างกาย",
  "Height (cm)": "ส่วนสูง (ซม.)",
  "Weight (kg)": "น้ำหนัก (กก.)",
  "Average Nightly Sleep (Hours)": "ชั่วโมงนอนเฉลี่ยต่อคืน",
  "Vegetable/Fruit Portions per Day": "ผัก/ผลไม้ต่อวัน (ส่วน)",
  "Water Intake per Day (Liters)": "น้ำดื่มต่อวัน (ลิตร)",
  "Weekly Physical Activity (IPAQ)": "กิจกรรมทางกายรายสัปดาห์ (IPAQ)",
  "Vigorous Exercise (Days/Week)": "ออกกำลังหนัก (วัน/สัปดาห์)",
  "Vigorous Minutes per Day": "นาทีที่ออกกำลังหนักต่อวัน",
  "Moderate Exercise (Days/Week)": "ออกกำลังปานกลาง (วัน/สัปดาห์)",
  "Moderate Minutes per Day": "นาทีที่ออกกำลังปานกลางต่อวัน",
  "Walking (Days/Week)": "เดิน (วัน/สัปดาห์)",
  "Walking Minutes per Day": "นาทีที่เดินต่อวัน",
  "Step 3: Mental Well-Being": "ขั้นที่ 3: สุขภาพจิต",
  "Step 4: Relationships": "ขั้นที่ 4: ความสัมพันธ์",
  "Step 5: Goals & Learning": "ขั้นที่ 5: เป้าหมายและการเรียนรู้",
  "Weekly Learning / Study Hours": "ชั่วโมงเรียนรู้/ศึกษาต่อสัปดาห์",
  "Digital Literacy Self-Rating (0-100)": "ประเมินทักษะดิจิทัลของตนเอง (0-100)",
  "Step 6: Contribution, Environment & Future": "ขั้นที่ 6: สังคม สิ่งแวดล้อม และอนาคต",
  "Monthly Donations (THB)": "เงินบริจาคต่อเดือน (บาท)",
  "Volunteering Hours per Month": "ชั่วโมงจิตอาสาต่อเดือน",
  "Single-Use Plastic Items per Day": "พลาสติกใช้ครั้งเดียวต่อวัน (ชิ้น)",
  "Long-term pension / retirement products (SSF, RMF, stock portfolio)?": "มีผลิตภัณฑ์บำนาญ/เกษียณระยะยาว (SSF, RMF, พอร์ตหุ้น) หรือไม่?",
  "No, not yet planning pension": "ยังไม่มี ยังไม่ได้วางแผนเกษียณ",
  "Yes, retirement assets secured": "มีแล้ว มีสินทรัพย์เพื่อเกษียณ",
  "Back": "ย้อนกลับ",
  "Next": "ถัดไป",
  "Complete Assessment": "ทำแบบประเมินให้เสร็จ",
  "Assessment Error: ": "แบบประเมินผิดพลาด: ",

  // --- Survey option scales ---
  "Describes me completely": "ตรงกับฉันที่สุด",
  "Describes me very well": "ตรงกับฉันมาก",
  "Somewhat": "ปานกลาง",
  "Very little": "ตรงเพียงเล็กน้อย",
  "Not at all": "ไม่ตรงเลย",
  "Always": "เสมอ",
  "Often": "บ่อยครั้ง",
  "Sometimes": "บางครั้ง",
  "Rarely": "นาน ๆ ครั้ง",
  "Never": "ไม่เคย",
  "Very often": "บ่อยมาก",
  "Rarely / Not at all": "แทบไม่มี / ไม่มีเลย",
  "1-3 days": "1-3 วัน",
  "4-14 days": "4-14 วัน",
  "Almost every day": "เกือบทุกวัน",
  "Regularly": "เป็นประจำ",
  "All of the time": "ตลอดเวลา",
  "Most of the time": "เกือบตลอดเวลา",
  "More than half the time": "มากกว่าครึ่งหนึ่งของเวลา",
  "Less than half the time": "น้อยกว่าครึ่งหนึ่งของเวลา",
  "Some of the time": "เป็นบางครั้ง",
  "At no time": "ไม่มีเลย",
  "None": "ไม่มี",
  "One": "1 คน",
  "Two": "2 คน",
  "Three or four": "3-4 คน",
  "Five to eight": "5-8 คน",
  "Nine or more": "9 คนขึ้นไป",
  "Hardly ever": "แทบไม่เคย",
  "Very poorly": "แย่มาก",
  "Poorly": "ค่อนข้างแย่",
  "Average": "ปานกลาง",
  "Well": "ดี",
  "Extremely well": "ดีมาก",
  "Not at all true": "ไม่จริงเลย",
  "Hardly true": "แทบไม่จริง",
  "Moderately true": "ค่อนข้างจริง",
  "Exactly true": "จริงที่สุด",
  "Not like me at all": "ไม่เหมือนฉันเลย",
  "Not much like me": "ไม่ค่อยเหมือนฉัน",
  "Somewhat like me": "เหมือนฉันบ้าง",
  "Mostly like me": "ค่อนข้างเหมือนฉัน",
  "Very much like me": "เหมือนฉันมาก",

  // --- Instrument titles ---
  "CFPB Financial Well-Being Assessment": "แบบประเมินสุขภาวะทางการเงิน (CFPB)",
  "Sleep Quality (past 2-4 weeks)": "คุณภาพการนอน (2-4 สัปดาห์ที่ผ่านมา)",
  "ST-5 Stress Index (past 2-4 weeks)": "แบบประเมินความเครียด ST-5 (2-4 สัปดาห์ที่ผ่านมา)",
  "WHO-5 Well-Being Index (past 2 weeks)": "ดัชนีสุขภาวะ WHO-5 (2 สัปดาห์ที่ผ่านมา)",
  "LSNS-6 Social Network Scale": "แบบวัดเครือข่ายสังคม LSNS-6",
  "UCLA Loneliness Index": "แบบวัดความเหงา UCLA",
  "Relationship Assessment (couples only)": "แบบประเมินความสัมพันธ์ (เฉพาะคนมีคู่)",
  "GSE-6 Self-Efficacy Scale": "แบบวัดการรับรู้ความสามารถของตนเอง GSE-6",
  "Grit-S (Perseverance)": "แบบวัดความมุ่งมั่น Grit-S",
  "Prosocial Tendencies (typical month)": "พฤติกรรมเพื่อสังคม (ในเดือนทั่วไป)",
  "Green Everyday Behavior": "พฤติกรรมรักษ์โลกในชีวิตประจำวัน",
  "Long-Term Future Index": "ดัชนีการมองอนาคตระยะยาว",

  // --- Instrument items ---
  "Because of my money situation, I feel like I will never have the things I want in life.": "เพราะสถานะการเงินของฉัน ฉันรู้สึกว่าคงไม่มีวันได้สิ่งที่ต้องการในชีวิต",
  "I am just getting by financially.": "ฉันแค่พอประทังตัวไปเดือนต่อเดือน",
  "I am concerned that the money I have or will save won't last.": "ฉันกังวลว่าเงินที่มีหรือที่จะเก็บออมจะไม่พอใช้ในระยะยาว",
  "I have money left over at the end of the month.": "ฉันมีเงินเหลือตอนสิ้นเดือน",
  "My finances control my life.": "เรื่องเงินควบคุมชีวิตของฉัน",
  "How often did you have difficulty falling asleep?": "คุณนอนหลับยากบ่อยแค่ไหน?",
  "How often did you wake up during the night?": "คุณตื่นกลางดึกบ่อยแค่ไหน?",
  "How often did you wake up earlier than planned?": "คุณตื่นเช้ากว่าที่ตั้งใจบ่อยแค่ไหน?",
  "How often did you wake up feeling unrefreshed?": "คุณตื่นมาแล้วรู้สึกไม่สดชื่นบ่อยแค่ไหน?",
  "How often did you have trouble sleeping because of worry?": "มีปัญหาการนอน นอนไม่หลับเพราะคิดมากหรือกังวลใจ บ่อยแค่ไหน?",
  "How often did you have poor concentration?": "มีสมาธิน้อยลง บ่อยแค่ไหน?",
  "How often did you feel irritable, restless, or agitated?": "หงุดหงิด กระวนกระวาย ว้าวุ่นใจ บ่อยแค่ไหน?",
  "How often did you feel bored or discouraged?": "รู้สึกเบื่อ เซ็ง ท้อแท้ บ่อยแค่ไหน?",
  "How often did you not want to meet people?": "ไม่อยากพบปะผู้คน บ่อยแค่ไหน?",
  "I have felt cheerful and in good spirits.": "ฉันรู้สึกร่าเริงและอารมณ์ดี",
  "I have felt calm and relaxed.": "ฉันรู้สึกสงบและผ่อนคลาย",
  "I have felt active and vigorous.": "ฉันรู้สึกกระฉับกระเฉงและมีพลัง",
  "I woke up feeling fresh and rested.": "ฉันตื่นนอนอย่างสดชื่นและรู้สึกได้พักผ่อนเต็มที่",
  "My daily life has been filled with things that interest me.": "ชีวิตประจำวันของฉันเต็มไปด้วยสิ่งที่น่าสนใจ",
  "How many relatives do you see or hear from at least once a month?": "มีญาติกี่คนที่คุณได้พบหรือติดต่อกันอย่างน้อยเดือนละครั้ง?",
  "How many relatives do you feel at ease with to talk about private matters?": "มีญาติกี่คนที่คุณสบายใจพอจะคุยเรื่องส่วนตัวด้วย?",
  "How many relatives do you feel close to such that you could call on them for help?": "มีญาติกี่คนที่สนิทพอจะขอความช่วยเหลือได้?",
  "How many friends do you see or hear from at least once a month?": "มีเพื่อนกี่คนที่คุณได้พบหรือติดต่อกันอย่างน้อยเดือนละครั้ง?",
  "How many friends do you feel at ease with to talk about private matters?": "มีเพื่อนกี่คนที่คุณสบายใจพอจะคุยเรื่องส่วนตัวด้วย?",
  "How many friends do you feel close to such that you could call on them for help?": "มีเพื่อนกี่คนที่สนิทพอจะขอความช่วยเหลือได้?",
  "How often do you feel that you lack companionship?": "คุณรู้สึกขาดเพื่อนหรือคนใกล้ชิดบ่อยแค่ไหน?",
  "How often do you feel left out?": "คุณรู้สึกถูกทิ้งไว้ข้างหลังบ่อยแค่ไหน?",
  "How often do you feel isolated from others?": "คุณรู้สึกโดดเดี่ยวแปลกแยกจากคนอื่นบ่อยแค่ไหน?",
  "How well does your partner meet your needs?": "คู่ของคุณตอบสนองความต้องการของคุณได้ดีแค่ไหน?",
  "In general, how satisfied are you with your relationship?": "โดยรวมแล้วคุณพึงพอใจกับความสัมพันธ์ของคุณแค่ไหน?",
  "How good is your relationship compared to most?": "ความสัมพันธ์ของคุณดีแค่ไหนเมื่อเทียบกับคู่อื่น ๆ?",
  "I can always manage to solve difficult problems if I try hard enough.": "ฉันสามารถแก้ปัญหาที่ยากได้เสมอ ถ้าฉันพยายามมากพอ",
  "If someone opposes me, I can find the means and ways to get what I want.": "หากมีใครขัดขวาง ฉันก็หาหนทางเพื่อให้ได้สิ่งที่ต้องการได้",
  "I am confident that I could deal efficiently with unexpected events.": "ฉันมั่นใจว่าจะรับมือกับเหตุการณ์ที่ไม่คาดคิดได้อย่างมีประสิทธิภาพ",
  "Thanks to my resourcefulness, I know how to handle unforeseen situations.": "ด้วยไหวพริบของฉัน ฉันรู้วิธีจัดการกับสถานการณ์ที่ไม่คาดฝัน",
  "I can solve most problems if I invest the necessary effort.": "ฉันแก้ปัญหาส่วนใหญ่ได้ ถ้าทุ่มเทความพยายามเท่าที่จำเป็น",
  "I can usually handle whatever comes my way.": "ฉันมักรับมือกับสิ่งที่ผ่านเข้ามาได้เสมอ",
  "I finish whatever I begin.": "ฉันทำสิ่งที่เริ่มไว้ให้เสร็จเสมอ",
  "Setbacks don't discourage me. I don't give up easily.": "อุปสรรคไม่ทำให้ฉันท้อ ฉันไม่ยอมแพ้ง่าย ๆ",
  "I am a hard worker.": "ฉันเป็นคนขยัน",
  "I am diligent. I never give up.": "ฉันมุ่งมั่นพากเพียร ไม่เคยยอมแพ้",
  "How often do you donate money to charity, temples, or people in need?": "คุณบริจาคเงินให้การกุศล วัด หรือผู้เดือดร้อนบ่อยแค่ไหน?",
  "How often do you help friends or family members who are in need?": "คุณช่วยเหลือเพื่อนหรือครอบครัวที่เดือดร้อนบ่อยแค่ไหน?",
  "How often do you help strangers (e.g., giving directions, carrying things)?": "คุณช่วยเหลือคนแปลกหน้า (เช่น บอกทาง ช่วยถือของ) บ่อยแค่ไหน?",
  "How often do you participate in community or neighborhood activities?": "คุณเข้าร่วมกิจกรรมชุมชนหรือละแวกบ้านบ่อยแค่ไหน?",
  "How often do you engage in local civic issues (e.g., voting, community meetings)?": "คุณมีส่วนร่วมในประเด็นบ้านเมือง (เช่น เลือกตั้ง ประชุมชุมชน) บ่อยแค่ไหน?",
  "How often do you separate recyclables (plastic, paper, glass) from general waste?": "คุณแยกขยะรีไซเคิล (พลาสติก กระดาษ แก้ว) ออกจากขยะทั่วไปบ่อยแค่ไหน?",
  "How often do you refuse or avoid single-use plastics (bags, straws, cups)?": "คุณปฏิเสธหรือหลีกเลี่ยงพลาสติกใช้ครั้งเดียว (ถุง หลอด แก้ว) บ่อยแค่ไหน?",
  "How often do you use public transit, walk, or cycle instead of a private car?": "คุณใช้ขนส่งสาธารณะ เดิน หรือปั่นจักรยานแทนรถส่วนตัวบ่อยแค่ไหน?",
  "How often do you turn off lights and appliances when not in use?": "คุณปิดไฟและเครื่องใช้ไฟฟ้าเมื่อไม่ใช้งานบ่อยแค่ไหน?",
  "How often do you limit air-conditioning use or set it to 25°C or higher?": "คุณจำกัดการใช้แอร์หรือตั้งอุณหภูมิ 25°C ขึ้นไปบ่อยแค่ไหน?",
  "How often do you choose eco-friendly or refillable products?": "คุณเลือกสินค้ารักษ์โลกหรือแบบเติมได้บ่อยแค่ไหน?",
  "I actively learn skills that will stay relevant in the future (AI, data, languages).": "ฉันเรียนรู้ทักษะที่จะยังสำคัญในอนาคตอย่างจริงจัง (AI ข้อมูล ภาษา)",
  "I do things intended to leave a positive legacy beyond my own life.": "ฉันทำสิ่งที่ตั้งใจให้เป็นมรดกที่ดีเกินอายุขัยของตัวเอง",
  "I support or donate to causes addressing future generations' well-being.": "ฉันสนับสนุนหรือบริจาคให้ประเด็นที่ดูแลความเป็นอยู่ของคนรุ่นหลัง",
  "I plan my finances with a horizon of 10 years or more.": "ฉันวางแผนการเงินโดยมองไกล 10 ปีขึ้นไป",
  "I support causes addressing global existential risks (climate, pandemics, AI safety).": "ฉันสนับสนุนประเด็นความเสี่ยงระดับโลก (สภาพภูมิอากาศ โรคระบาด ความปลอดภัยของ AI)",

  // --- Routine presets ---
  "Add to Savings": "หยอดเงินออม",
  "Deposit money/savings (+8 Finance)": "ฝากเงิน/เงินออม (+8 การเงิน)",
  "Amount saved": "จำนวนเงินที่ออม",
  "THB": "บาท",
  "CBT Journaling": "เขียนบันทึก CBT",
  "Write cognitive reappraisal (+8 Mental)": "เขียนปรับมุมมองความคิด (+8 จิตใจ)",
  "Physiological Sigh": "ถอนหายใจคลายเครียด",
  "Breath control vagus reset (+5 Mental)": "ฝึกลมหายใจรีเซ็ตระบบประสาท (+5 จิตใจ)",
  "Exercise Session": "ออกกำลังกาย",
  "Exercise MVPA (+10 Phys, +3 Mental)": "ออกกำลังระดับปานกลาง-หนัก (+10 ร่างกาย +3 จิตใจ)",
  "Duration": "ระยะเวลา",
  "minutes": "นาที",
  "Veggie Portions": "กินผักผลไม้",
  "Eat healthy greens (+5 Physical)": "กินผักผลไม้เพื่อสุขภาพ (+5 ร่างกาย)",
  "Portions today": "จำนวนส่วนวันนี้",
  "portions": "ส่วน",
  "Water Intake": "ดื่มน้ำ",
  "Hydration target (+5 Physical)": "ดื่มน้ำให้ถึงเป้า (+5 ร่างกาย)",
  "Amount today": "ปริมาณวันนี้",
  "liters": "ลิตร",
  "Connect with Friend": "ติดต่อเพื่อน",
  "Call relative or friend (+10 Rel, +2 Ment)": "โทรหาญาติหรือเพื่อน (+10 ความสัมพันธ์ +2 จิตใจ)",
  "Relationship Date": "เดตกับคู่รัก",
  "Quality partner time (+8 Relationships)": "เวลาคุณภาพกับคู่ (+8 ความสัมพันธ์)",
  "Make Merit / Donation": "ทำบุญ / บริจาค",
  "Tham Bun / Donate (+10 Social, -2 Fin)": "ทำบุญ/บริจาค (+10 สังคม -2 การเงิน)",
  "Amount donated": "จำนวนเงินบริจาค",
  "Volunteer": "จิตอาสา",
  "Community service (+12 Social)": "งานอาสาเพื่อชุมชน (+12 สังคม)",
  "Time spent": "เวลาที่ใช้",
  "hours": "ชั่วโมง",
  "Separate Recycling": "แยกขยะรีไซเคิล",
  "Household waste sort (+8 Env)": "แยกขยะในบ้าน (+8 สิ่งแวดล้อม)",
  "Ride BTS / MRT": "นั่ง BTS / MRT",
  "Avoid car commute (+8 Env)": "เลี่ยงการใช้รถส่วนตัว (+8 สิ่งแวดล้อม)",
  "Study AI / Data Sci": "เรียน AI / วิทยาการข้อมูล",
  "Upskill future tech (+10 Future, +5 Goals)": "อัปสกิลเทคโนโลยีอนาคต (+10 อนาคต +5 เป้าหมาย)",
  "Study time": "เวลาเรียน",
  "Mentor / Teach": "สอน / เป็นพี่เลี้ยง",
  "Share upskilling (+8 Future, +2 Rel)": "ถ่ายทอดความรู้ (+8 อนาคต +2 ความสัมพันธ์)",

  // --- Missions ---
  "Stay Hydrated": "ดื่มน้ำให้พอ",
  "Log your 2L+ hydration once today.": "บันทึกการดื่มน้ำ 2 ลิตรขึ้นไปวันนี้ 1 ครั้ง",
  "Breath Control": "ควบคุมลมหายใจ",
  "Log 3 physiological sighs to reset stress.": "บันทึกการถอนหายใจคลายเครียด 3 ครั้ง",
  "Active Core": "ขยับให้ครบ",
  "Log at least 3 exercise sessions this week.": "บันทึกการออกกำลังกายอย่างน้อย 3 ครั้งในสัปดาห์นี้",
  "Safety Deposit": "เงินฝากนิรภัย",
  "Log a savings deposit 10 times.": "บันทึกการฝากเงินออม 10 ครั้ง",
  "3 deposits logged": "ฝากแล้ว 3 ครั้ง",
  "6 deposits logged": "ฝากแล้ว 6 ครั้ง",
  "10 deposits logged": "ฝากแล้ว 10 ครั้ง",
  "DAILY": "รายวัน",
  "WEEKLY": "รายสัปดาห์",
  "EPIC": "มหากาพย์",
  "Active Goals": "เป้าหมายที่กำลังทำ",
  "Goals progress automatically as you log matching routines. Daily goals reset each day, weekly goals each week.":
    "เป้าหมายคืบหน้าอัตโนมัติเมื่อคุณบันทึกกิจวัตรที่เกี่ยวข้อง เป้าหมายรายวันรีเซ็ตทุกวัน รายสัปดาห์รีเซ็ตทุกสัปดาห์",
  "All goals completed. New cycles begin tomorrow.": "ทำเป้าหมายครบแล้ว รอบใหม่เริ่มพรุ่งนี้",
  "Aspect: {aspect} • +{xp} points": "ด้าน: {aspect} • +{xp} คะแนน",
  "{current} / {target} logged": "บันทึกแล้ว {current} / {target}",
  "Completed Goals": "เป้าหมายที่สำเร็จ",
  "No completed goals in this cycle yet.": "ยังไม่มีเป้าหมายที่สำเร็จในรอบนี้",
  "Completed: +{xp} points": "สำเร็จ: +{xp} คะแนน",

  // --- Dashboard ---
  "Erase all data": "ลบข้อมูลทั้งหมด",
  "Erase all data?": "ลบข้อมูลทั้งหมดหรือไม่",
  "This deletes every logged routine, your goals, and your baseline assessment.": "การดำเนินการนี้จะลบกิจวัตรที่บันทึกไว้ทั้งหมด เป้าหมาย และผลประเมินพื้นฐานของคุณ",
  "It cannot be undone, and this browser holds the only copy.": "ไม่สามารถกู้คืนได้ และเบราว์เซอร์นี้เก็บข้อมูลสำเนาเดียวเท่านั้น",
  "Download a backup, then erase": "ดาวน์โหลดไฟล์สำรอง แล้วจึงลบ",
  "Erase without a backup": "ลบโดยไม่สำรองข้อมูล",
  "Back up your data.": "สำรองข้อมูลของคุณ",
  "Everything here is stored only in this browser. Clearing site data, or the browser reclaiming space, would erase it with no way back.": "ข้อมูลทั้งหมดถูกเก็บไว้ในเบราว์เซอร์นี้เท่านั้น หากล้างข้อมูลเว็บไซต์หรือเบราว์เซอร์เรียกคืนพื้นที่ ข้อมูลจะถูกลบโดยกู้คืนไม่ได้",
  "Your last backup was {days} days ago. Everything here is stored only in this browser, so a cleared cache would erase it.": "คุณสำรองข้อมูลครั้งล่าสุดเมื่อ {days} วันที่แล้ว ข้อมูลทั้งหมดถูกเก็บไว้ในเบราว์เซอร์นี้เท่านั้น การล้างแคชจะลบข้อมูลทิ้ง",
  "Monthly re-assessment due.": "ถึงเวลาประเมินซ้ำประจำเดือนแล้ว",
  "Re-run the short well-being instruments so your scores track your real standing, not last month's.":
    "ทำแบบประเมินชุดสั้นอีกครั้ง เพื่อให้คะแนนสะท้อนสถานะจริงของคุณ ไม่ใช่ของเดือนที่แล้ว",
  "Start Re-assessment": "เริ่มประเมินซ้ำ",
  "Experience progress": "ความคืบหน้าคะแนน",
  "Progress: {pct}%": "ความคืบหน้า: {pct}%",
  "Weekly Commitment": "คำมั่นประจำสัปดาห์",
  "Aspect Radar": "เรดาร์รายด้าน",
  "Recommendations": "คำแนะนำ",
  "Targeting your weakest measured components — tap one to open that aspect.": "เจาะจงองค์ประกอบที่อ่อนที่สุดของคุณ — แตะเพื่อเปิดด้านนั้น",
  "Aspect Scores": "คะแนนรายด้าน",
  "Open {aspect} details": "เปิดรายละเอียดด้าน{aspect}",
  "Society: ~{pct} percentile": "สังคม: ~เปอร์เซ็นไทล์{pct}",
  "vs published norms": "เทียบเกณฑ์ที่ตีพิมพ์",
  "vs participation rates": "เทียบอัตราการมีส่วนร่วม",
  "estimate": "ค่าประมาณ",
  "Benchmark sources & methodology": "แหล่งอ้างอิงและวิธีการเทียบ",
  'Percentiles compare your baseline answers with published population statistics — they are honest approximations, not exact ranks. "Estimate" marks curves calibrated to a published anchor point.':
    'เปอร์เซ็นไทล์เทียบคำตอบพื้นฐานของคุณกับสถิติประชากรที่ตีพิมพ์ — เป็นค่าประมาณอย่างตรงไปตรงมา ไม่ใช่อันดับที่แน่นอน ป้าย "ค่าประมาณ" หมายถึงเส้นโค้งที่ปรับเทียบกับจุดอ้างอิงที่ตีพิมพ์',
  "Recent Activity": "กิจกรรมล่าสุด",
  "No logs recorded yet. Ledger is clean.": "ยังไม่มีบันทึก สมุดยังว่างอยู่",
  "Logged:": "บันทึก:",
  "Reward +{xp} points.": "รางวัล +{xp} คะแนน",

  // --- Commitment pin ---
  "{aspect} • this week": "{aspect} • สัปดาห์นี้",
  "Commitment progress": "ความคืบหน้าคำมั่น",
  "✅ Pledge complete — bonus points banked. Resets next week.": "✅ ทำตามคำมั่นสำเร็จ — รับโบนัสคะแนนแล้ว เริ่มใหม่สัปดาห์หน้า",
  "Log {n} more {aspect} routine(s) for +{xp} bonus points.": "บันทึกกิจวัตรด้าน{aspect}อีก {n} ครั้ง เพื่อรับโบนัส +{xp} คะแนน",

  // --- Aspect pages ---
  "Log {title}": "บันทึก {title}",
  "Remove routine": "ลบกิจวัตร",
  "Standing vs Society": "สถานะเทียบกับสังคม",
  "Percentile vs society": "เปอร์เซ็นไทล์เทียบสังคม",
  "~{pct} percentile": "~เปอร์เซ็นไทล์{pct}",
  "Sources": "แหล่งอ้างอิง",
  "No baseline data for this comparison yet — re-run the onboarding sync to unlock it.": "ยังไม่มีข้อมูลพื้นฐานสำหรับการเทียบนี้ — ทำแบบประเมินแรกเข้าใหม่เพื่อปลดล็อก",
  "Component Breakdown": "องค์ประกอบย่อย",
  "Baseline survey data needed for this breakdown.": "ต้องมีข้อมูลแบบประเมินพื้นฐานจึงจะแสดงส่วนนี้ได้",
  "Suggested Focus": "จุดที่ควรโฟกัส",
  "End Commitment": "ยกเลิกคำมั่น",
  "You're already committed to {link} this week — one pledge at a time keeps it honest.":
    "สัปดาห์นี้คุณให้คำมั่นกับด้าน{link}อยู่แล้ว — ทีละหนึ่งคำมั่นถึงจะทำได้จริง",
  "Pledge a weekly routine count for {aspect}. Hitting it earns bonus points; the pledge renews every week until you end it.":
    "ตั้งคำมั่นจำนวนกิจวัตรต่อสัปดาห์สำหรับด้าน{aspect} ทำถึงเป้าได้โบนัสคะแนน และคำมั่นจะต่ออายุทุกสัปดาห์จนกว่าคุณจะยกเลิก",
  "Routine logs per week (3-21)": "จำนวนบันทึกต่อสัปดาห์ (3-21)",
  "Commit": "ให้คำมั่น",
  "Trend (Weekly Snapshots)": "แนวโน้ม (ภาพรวมรายสัปดาห์)",
  "Log a {aspect} Routine": "บันทึกกิจวัตรด้าน{aspect}",
  "No routines target this aspect yet — register one in the Routines Ledger.": "ยังไม่มีกิจวัตรสำหรับด้านนี้ — ลงทะเบียนได้ในสมุดกิจวัตร",
  "End this week's commitment? Progress will be discarded.": "ยกเลิกคำมั่นของสัปดาห์นี้? ความคืบหน้าจะถูกลบ",
  "No snapshots yet — trends appear after your first weekly sync.": "ยังไม่มีภาพรวม — แนวโน้มจะแสดงหลังซิงก์รายสัปดาห์ครั้งแรก",

  // --- Confidence & completeness (Phase 2) ---
  "High": "สูง",
  "Partial": "บางส่วน",
  "Estimated": "ประมาณการ",
  "Score confidence: {answered} of {total} inputs answered": "ความเชื่อมั่นของคะแนน: ตอบแล้ว {answered} จาก {total} รายการ",
  "{answered}/{total} inputs answered": "ตอบแล้ว {answered}/{total} รายการ",
  "Some scores are estimates.": "บางคะแนนเป็นค่าประมาณ",
  "These are scored from default answers: {aspects}. Re-run your assessment or log related routines to confirm them.":
    "คะแนนเหล่านี้คิดจากคำตอบเริ่มต้น: {aspects} ทำแบบประเมินใหม่หรือบันทึกกิจวัตรที่เกี่ยวข้องเพื่อยืนยัน",
  "Estimated score.": "คะแนนประมาณการ",
  "This score comes from default answers. Answer the {aspect} questions or log routines to confirm it.":
    "คะแนนนี้มาจากคำตอบเริ่มต้น ตอบคำถามด้าน{aspect}หรือบันทึกกิจวัตรเพื่อยืนยัน",

  // --- Monthly re-sync page ---
  "MONTHLY RE-ASSESSMENT": "การประเมินซ้ำประจำเดือน",
  "Short instruments only • recalibrates Mental, Relationships & Personal Goals": "แบบประเมินชุดสั้น • ปรับเทียบด้านจิตใจ ความสัมพันธ์ และเป้าหมายส่วนตัว",
  "Answer for the recent weeks, not how you felt at onboarding. Scores shift by at most ±15 points per re-assessment, and consistent routine logging since the last one adds a small bonus. Reward: +40 points.":
    "ตอบตามช่วงสัปดาห์ที่ผ่านมา ไม่ใช่ความรู้สึกตอนแรกเข้า คะแนนขยับได้ไม่เกิน ±15 แต้มต่อการประเมินซ้ำ และการบันทึกกิจวัตรสม่ำเสมอตั้งแต่ครั้งก่อนจะได้โบนัสเล็กน้อย รางวัล: +40 คะแนน",
  "Complete Re-assessment": "เสร็จสิ้นการประเมินซ้ำ",
  "Re-assessment Error: ": "การประเมินซ้ำผิดพลาด: ",

  // --- Routines ledger ---
  "Log Routine": "บันทึกกิจวัตร",
  "Select a routine below to record it. Your aspect scores update automatically (max 5 logs per routine per day).":
    "เลือกกิจวัตรด้านล่างเพื่อบันทึก คะแนนรายด้านของคุณจะอัปเดตอัตโนมัติ (สูงสุด 5 ครั้งต่อกิจวัตรต่อวัน)",
  "Register New Routine": "ลงทะเบียนกิจวัตรใหม่",
  "Registered routines appear in the routine grid and can be logged like presets.": "กิจวัตรที่ลงทะเบียนจะปรากฏในตารางและบันทึกได้เหมือนรายการสำเร็จรูป",
  "Routine Name": "ชื่อกิจวัตร",
  "E.g., Practice Meditating": "เช่น ฝึกนั่งสมาธิ",
  "Target Aspect": "ด้านที่ต้องการพัฒนา",
  "Aspect Sync Impact (+1 to +15)": "ผลต่อค่าด้าน (+1 ถึง +15)",
  "Points Reward (+5 to +50)": "รางวัลคะแนน (+5 ถึง +50)",
  "Register Routine": "ลงทะเบียนกิจวัตร",
  "Enter the real amount — it becomes part of your measured record.": "กรอกจำนวนจริง — จะถูกเก็บเป็นข้อมูลที่วัดได้ของคุณ",
  "Cancel": "ยกเลิก",
  "Log It": "บันทึกเลย",
  'Daily limit reached for "{name}" (max {max} logs). Take a break and return tomorrow.': 'วันนี้บันทึก "{name}" ครบแล้ว (สูงสุด {max} ครั้ง) พักก่อนแล้วค่อยกลับมาใหม่พรุ่งนี้',

  // --- Rankings / Crew Codes ---
  "Comparison Codes": "รหัสเปรียบเทียบ",
  "Peer comparison uses <strong>real people</strong>: share your code with others over LINE or Discord, and paste theirs below. Codes carry only your name, level, points, and aspect scores — nothing private. Re-paste a newer code any time to update a participant.":
    "การเปรียบเทียบกับผู้อื่นใช้<strong>คนจริง</strong>: แชร์รหัสของคุณให้ผู้อื่นทาง LINE หรือ Discord แล้วนำรหัสของพวกเขามาวางด้านล่าง รหัสมีแค่ชื่อ เลเวล คะแนน และคะแนนรายด้าน — ไม่มีข้อมูลส่วนตัว วางรหัสใหม่ได้ทุกเมื่อเพื่ออัปเดตผู้เข้าร่วม",
  "Your Comparison Code": "รหัสเปรียบเทียบของคุณ",
  "Copy": "คัดลอก",
  "Copied!": "คัดลอกแล้ว!",
  "Add a participant's code": "เพิ่มรหัสของผู้เข้าร่วม",
  "Add": "เพิ่ม",
  "No participants added yet — sample profiles fill the board until you add codes.": "ยังไม่มีผู้เข้าร่วม — โปรไฟล์ตัวอย่างจะเติมกระดานจนกว่าคุณจะเพิ่มรหัส",
  "{n} participant added. Sample rows are marked.": "เพิ่มผู้เข้าร่วม {n} คน แถวตัวอย่างมีป้ายกำกับ",
  "{n} participants added. Sample rows are marked.": "เพิ่มผู้เข้าร่วม {n} คน แถวตัวอย่างมีป้ายกำกับ",
  "Rank": "อันดับ",
  "Participant": "ผู้เข้าร่วม",
  "Level": "เลเวล",
  "Total Points": "คะแนนรวม",
  "Tier": "ระดับ",
  "Sample": "ตัวอย่าง",
  "{name} (You)": "{name} (คุณ)",
  "Remove {name}": "ลบ {name}",
  "Remove participant": "ลบผู้เข้าร่วม",
  "Participant list is full (max {max}).": "รายชื่อผู้เข้าร่วมเต็มแล้ว (สูงสุด {max} คน)",
  'Comparison codes start with "{prefix}".': 'รหัสเปรียบเทียบต้องขึ้นต้นด้วย "{prefix}"',
  "That code is damaged — ask the participant to copy it again.": "รหัสนี้เสียหาย — ให้ผู้เข้าร่วมคัดลอกส่งมาใหม่อีกครั้ง",
  "Unsupported comparison code version.": "เวอร์ชันรหัสเปรียบเทียบไม่รองรับ",
  "Comparison code is missing a name.": "รหัสเปรียบเทียบไม่มีชื่อ",
  "Comparison code has an invalid level.": "รหัสเปรียบเทียบมีเลเวลไม่ถูกต้อง",
  "Comparison code has invalid points.": "รหัสเปรียบเทียบมีคะแนนไม่ถูกต้อง",
  "Comparison code has invalid aspect scores.": "รหัสเปรียบเทียบมีคะแนนรายด้านไม่ถูกต้อง",
  "Nadia": "นาเดีย",
  "Marcus": "มาร์คัส",
  "Priya": "ปรียา",
  "Kenji": "เคนจิ",
  "Sofia": "โซเฟีย",
  "Liam": "เลียม",

  // --- Backup / import errors ---
  "File is not valid JSON.": "ไฟล์ไม่ใช่ JSON ที่ถูกต้อง",
  "This file is not a valid backup (missing profile/aspects).": "ไฟล์นี้ไม่ใช่ข้อมูลสำรองที่ถูกต้อง (ไม่มี profile/aspects)",
  "Backup schema v{found} is not compatible with v{expected}.": "ข้อมูลสำรองสคีมา v{found} ไม่เข้ากันกับ v{expected}",

  // --- Guidance assistant dialogue ---
  "Your finance score has room to grow. A simple monthly budget and a set savings rate are good starting points.":
    "คะแนนการเงินของคุณยังพัฒนาได้อีก การทำงบรายเดือนง่าย ๆ และตั้งอัตราการออมเป็นจุดเริ่มต้นที่ดี",
  "Your physical activity could use a lift. A short walk today is an easy way to build momentum.":
    "กิจกรรมทางกายของคุณน่าจะเพิ่มได้อีก เดินสั้น ๆ วันนี้เป็นวิธีง่าย ๆ ในการสร้างแรงส่ง",
  "Feeling stretched? Try a slow breathing break — two short inhales through the nose, then one long exhale.":
    "รู้สึกตึงเครียดไหม? ลองพักหายใจช้า ๆ — สูดเข้าทางจมูกสั้น ๆ สองครั้ง แล้วผ่อนออกยาว ๆ หนึ่งครั้ง",
  "Connection matters. Consider reaching out to a close friend or relative this week.":
    "ความสัมพันธ์สำคัญ ลองติดต่อเพื่อนสนิทหรือญาติสักคนในสัปดาห์นี้",
  "Steady practice moves your goals forward. Even 20 minutes of focused learning today helps.":
    "การฝึกฝนสม่ำเสมอช่วยให้เป้าหมายก้าวหน้า แค่ตั้งใจเรียนรู้ 20 นาทีวันนี้ก็ช่วยได้",
  "Small acts of giving add up. A minor kindness or a modest donation strengthens this area.":
    "การให้เล็ก ๆ น้อย ๆ สะสมได้ น้ำใจเล็กน้อยหรือการบริจาคพอประมาณช่วยเสริมด้านนี้",
  "Everyday choices shape your footprint. Separating recyclables today is a simple step.":
    "ทางเลือกในแต่ละวันกำหนดรอยเท้าทางสิ่งแวดล้อมของคุณ การแยกขยะรีไซเคิลวันนี้เป็นก้าวง่าย ๆ",
  "Long-term security grows from consistent habits — saving and upskilling both anchor your future.":
    "ความมั่นคงระยะยาวเติบโตจากนิสัยที่สม่ำเสมอ — การออมและการอัปสกิลต่างช่วยยึดอนาคตของคุณ",
  "Log a routine today to keep your assessment current and track your progress.":
    "บันทึกกิจวัตรวันนี้เพื่อให้แบบประเมินของคุณเป็นปัจจุบันและติดตามความก้าวหน้า",

  // --- Component labels & details (aspects.js) ---
  "Income standing": "สถานะรายได้",
  "Percentile vs Thai worker earnings (estimate)": "เปอร์เซ็นไทล์เทียบรายได้แรงงานไทย (ค่าประมาณ)",
  "Financial well-being (CFPB)": "สุขภาวะทางการเงิน (CFPB)",
  "Raw {n}/20 at baseline": "คะแนนดิบ {n}/20 ณ จุดเริ่มต้น",
  "Savings habit": "นิสัยการออม",
  "Saving {rate}% of income (20%+ maxes this)": "ออม {rate}% ของรายได้ (20% ขึ้นไปได้เต็ม)",
  "Activity": "การเคลื่อนไหว",
  "{met} MET-min/week (WHO guideline 600)": "{met} MET-นาที/สัปดาห์ (เกณฑ์ WHO 600)",
  "Body composition": "องค์ประกอบร่างกาย",
  "Asian BMI bands (18.5-22.9 ideal)": "เกณฑ์ BMI เอเชีย (18.5-22.9 คือช่วงดี)",
  "Sleep": "การนอน",
  "{h}h/night + baseline quality {jss}/20 issues": "{h} ชม./คืน + ปัญหาคุณภาพการนอน {jss}/20 ณ จุดเริ่มต้น",
  "Sleep duration": "ระยะเวลานอน",
  "{h}h/night (7-9h ideal)": "{h} ชม./คืน (7-9 ชม. คือช่วงดี)",
  "Nutrition": "โภชนาการ",
  "{veg} veg portions, {water}L water/day": "ผัก {veg} ส่วน, น้ำ {water} ลิตร/วัน",
  "Well-being (WHO-5)": "สุขภาวะ (WHO-5)",
  "Raw {n}/25 at baseline (scores under 50/100 suggest low mood)": "คะแนนดิบ {n}/25 ณ จุดเริ่มต้น (ต่ำกว่า 50/100 บ่งชี้อารมณ์ซึม)",
  "Stress resilience (ST-5)": "ความทนทานต่อความเครียด (ST-5)",
  "Stress {n}/15 — DMH bands: 0-4 fine, 5-6 watch, 7+ problem": "ความเครียด {n}/15 — เกณฑ์กรมสุขภาพจิต: 0-4 ปกติ, 5-6 เฝ้าระวัง, 7 ขึ้นไปมีปัญหา",
  "Social network (LSNS-6)": "เครือข่ายสังคม (LSNS-6)",
  "Raw {n}/30 (under 12 = isolation risk)": "คะแนนดิบ {n}/30 (ต่ำกว่า 12 = เสี่ยงโดดเดี่ยว)",
  "Low loneliness (UCLA-3)": "ความเหงาต่ำ (UCLA-3)",
  "Loneliness {n}/9, inverted (higher bar = less lonely)": "ความเหงา {n}/9 กลับด้าน (แถบสูง = เหงาน้อย)",
  "Romantic satisfaction (RAS)": "ความพึงพอใจในความรัก (RAS)",
  "Raw {n}/15 at baseline": "คะแนนดิบ {n}/15 ณ จุดเริ่มต้น",
  "Self-efficacy (GSE)": "การรับรู้ความสามารถตนเอง (GSE)",
  "Raw {n}/24 at baseline": "คะแนนดิบ {n}/24 ณ จุดเริ่มต้น",
  "Grit": "ความมุ่งมั่น",
  "{g}/5 vs the ~3.4 adult reference": "{g}/5 เทียบจุดอ้างอิงผู้ใหญ่ ~3.4",
  "Active learning": "การเรียนรู้เชิงรุก",
  "{h}h/week study + digital skills {d}/100": "เรียน {h} ชม./สัปดาห์ + ทักษะดิจิทัล {d}/100",
  "Giving": "การให้",
  "{thb} THB/month (500+ maxes this)": "{thb} บาท/เดือน (500 ขึ้นไปได้เต็ม)",
  "Volunteering": "งานอาสา",
  "{h}h/month (4h+ maxes this)": "{h} ชม./เดือน (4 ชม. ขึ้นไปได้เต็ม)",
  "Prosocial habits (PTM)": "พฤติกรรมเพื่อสังคม (PTM)",
  "Plastic reduction": "การลดพลาสติก",
  "{n} single-use pieces/day (Thai avg ~3)": "พลาสติกใช้ครั้งเดียว {n} ชิ้น/วัน (เฉลี่ยไทย ~3)",
  "Green habits (GEB)": "นิสัยรักษ์โลก (GEB)",
  "Raw {n}/24 at baseline ": "คะแนนดิบ {n}/24 ณ จุดเริ่มต้น",
  "Future skills": "ทักษะแห่งอนาคต",
  "{h}h/week toward future-proof skills — reuses your weekly learning hours": "{h} ชม./สัปดาห์กับทักษะที่พร้อมรับอนาคต — ใช้ชั่วโมงการเรียนรู้รายสัปดาห์ร่วมกัน",
  "Long-term security": "ความมั่นคงระยะยาว",
  "Holds retirement/long-term investments": "มีการลงทุนเพื่อเกษียณ/ระยะยาว",
  "No retirement/long-term investments yet": "ยังไม่มีการลงทุนเพื่อเกษียณ/ระยะยาว",
  "Future orientation (LFIS)": "การมองการณ์ไกล (LFIS)",

  // --- Benchmarks (benchmarks.js) ---
  "Income of {income} THB/mo vs Bangkok workers": "รายได้ {income} บาท/เดือน เทียบกับแรงงานกรุงเทพฯ",
  "Income of {income} THB/mo vs Thai workers": "รายได้ {income} บาท/เดือน เทียบกับแรงงานไทย",
  "Lognormal curve calibrated to the Labour Force Survey average wage; NSO does not publish worker-level deciles openly.":
    "เส้นโค้ง lognormal ปรับเทียบกับค่าจ้างเฉลี่ยจากการสำรวจภาวะการทำงาน; สสช. ไม่เผยแพร่ข้อมูลเดไซล์รายบุคคล",
  "The income spread (log-sigma 0.65) is an assumed wage dispersion, not published decile data — the rank is approximate.":
    "การกระจายของรายได้ (log-sigma 0.65) เป็นค่าสมมติของการกระจายค่าจ้าง ไม่ใช่ข้อมูลเดไซล์ที่ตีพิมพ์ — อันดับจึงเป็นค่าโดยประมาณ",
  "{met} MET-min/week vs Thai adults (WHO guideline = 600)": "{met} MET-นาที/สัปดาห์ เทียบกับผู้ใหญ่ไทย (เกณฑ์ WHO = 600)",
  "BMI {bmi} — below the BMI-25 line that {share}% of Thai adults are over.": "BMI {bmi} — ต่ำกว่าเส้น BMI 25 ที่ผู้ใหญ่ไทย {share}% อยู่เหนือเส้นนี้",
  "BMI {bmi} — in the {share}% of Thai adults at BMI 25+.": "BMI {bmi} — อยู่ในกลุ่ม {share}% ของผู้ใหญ่ไทยที่ BMI 25 ขึ้นไป",
  'ST-5 stress score {n}/15 — "{band}" band on the Thai DMH scale.': 'คะแนนความเครียด ST-5 {n}/15 — อยู่ในเกณฑ์ "{band}" ของกรมสุขภาพจิต',
  "no stress problem": "ไม่มีปัญหาความเครียด",
  "possible stress problem": "อาจมีปัญหาความเครียด",
  "stress problem": "มีปัญหาความเครียด",
  "WHO-5 well-being {score}/100 vs general-population norms": "สุขภาวะ WHO-5 {score}/100 เทียบเกณฑ์ประชากรทั่วไป",
  "Percentile is against a German WHO-5 community sample — no representative Thai WHO-5 norm is published, so read it as indicative.":
    "เปอร์เซ็นไทล์เทียบกับกลุ่มตัวอย่างชุมชนเยอรมัน WHO-5 — ยังไม่มีเกณฑ์ WHO-5 ของไทยที่เป็นตัวแทน จึงควรถือเป็นค่าชี้แนวโน้มเท่านั้น",
  "range ≈ {low}–{high}": "ช่วงประมาณ {low}–{high}",
  "Deepen my survey scores": "เพิ่มความแม่นยำของคะแนนแบบสอบถาม",
  "The range is an indicative band reflecting the method's precision, not a statistical confidence interval.":
    "ช่วงนี้เป็นแถบโดยประมาณที่สะท้อนความแม่นยำของวิธีคำนวณ ไม่ใช่ช่วงความเชื่อมั่นทางสถิติ",
  "LSNS-6 score {n}/30 is under the social-isolation cutoff of 12.": "คะแนน LSNS-6 {n}/30 ต่ำกว่าจุดตัดภาวะโดดเดี่ยวทางสังคมที่ 12",
  "LSNS-6 score {n}/30 is above the social-isolation cutoff of 12.": "คะแนน LSNS-6 {n}/30 สูงกว่าจุดตัดภาวะโดดเดี่ยวทางสังคมที่ 12",
  "Loneliness (UCLA-3) and social network (LSNS-6) vs published community samples": "ความเหงา (UCLA-3) และเครือข่ายสังคม (LSNS-6) เทียบกับกลุ่มตัวอย่างที่ตีพิมพ์",
  "Grit {g}/5 vs the ~3.4 adult reference point.": "ความมุ่งมั่น {g}/5 เทียบจุดอ้างอิงผู้ใหญ่ ~3.4",
  "Self-efficacy (GSE) vs 25-country norms, N=19,120": "การรับรู้ความสามารถตนเอง (GSE) เทียบเกณฑ์ 25 ประเทศ N=19,120",
  "Your 6-item GSE is compared per-item against 10-item GSE norms — a short-form approximation, not an exact match.":
    "GSE แบบ 6 ข้อของคุณถูกเทียบรายข้อกับเกณฑ์ GSE แบบ 10 ข้อ — เป็นการประมาณจากแบบสั้น ไม่ใช่การเทียบที่ตรงกันพอดี",
  "Giving participation: {band}": "การมีส่วนร่วมในการให้: {band}",
  "donates and volunteers — inside the 19% of Thais who volunteer": "ทั้งบริจาคและอาสา — อยู่ในกลุ่ม 19% ของคนไทยที่ทำงานอาสา",
  "volunteers — inside the 19% of Thais who volunteer": "ทำงานอาสา — อยู่ในกลุ่ม 19% ของคนไทยที่ทำงานอาสา",
  "donates — inside the 52% of Thais who gave money": "บริจาค — อยู่ในกลุ่ม 52% ของคนไทยที่บริจาคเงิน",
  "no regular giving yet — 52% of Thais donated last year": "ยังไม่มีการให้เป็นประจำ — ปีที่แล้ว 52% ของคนไทยบริจาค",
  "Participation-rate placement, not an exact rank — CAF publishes yes/no rates, not amounts.":
    "จัดวางตามอัตราการมีส่วนร่วม ไม่ใช่อันดับที่แน่นอน — CAF เผยแพร่เพียงอัตราใช่/ไม่ใช่ ไม่ใช่จำนวนเงิน",
  "{pieces} single-use plastic pieces/day vs the ~3/day Thai average": "พลาสติกใช้ครั้งเดียว {pieces} ชิ้น/วัน เทียบค่าเฉลี่ยคนไทย ~3 ชิ้น/วัน",
  "Banded around the post-plastic-ban Thai average; per-person distribution data is not published.":
    "จัดช่วงรอบค่าเฉลี่ยคนไทยหลังมาตรการงดถุงพลาสติก; ไม่มีข้อมูลการแจกแจงรายบุคคลที่เผยแพร่",
  "Holds long-term retirement investments — ahead of most Thai workers": "มีการลงทุนเพื่อเกษียณระยะยาว — นำหน้าแรงงานไทยส่วนใหญ่",
  "No long-term retirement investments yet — like most Thai workers": "ยังไม่มีการลงทุนเพื่อเกษียณระยะยาว — เหมือนแรงงานไทยส่วนใหญ่",
  "Most Thai workers lack adequate retirement savings; ~2 in 3 over-60s get no social-security annuity.":
    "แรงงานไทยส่วนใหญ่มีเงินเก็บเกษียณไม่พอ; ผู้สูงวัย 60+ ราว 2 ใน 3 ไม่มีสิทธิ์รับบำนาญประกันสังคม",

  // --- Suggestions (suggestions.js) ---
  "Grow your savings rate": "เพิ่มอัตราการออม",
  "Even 5% of any money that comes in counts — set it aside the day you receive it, before spending.":
    "แม้แค่ 5% ของเงินที่เข้ามาก็มีค่า — แยกเก็บทันทีวันที่ได้รับ ก่อนเอาไปใช้",
  "Automate a transfer on payday so saving happens before spending — 15-20% of income maxes this component.":
    "ตั้งโอนอัตโนมัติทุกวันเงินเดือนออก ให้การออมเกิดก่อนการใช้ — ออม 15-20% ของรายได้จะได้คะแนนเต็มส่วนนี้",
  "Raise your earning power": "เพิ่มพลังการหารายได้",
  "Review your rates against the market and pitch one new client this month — freelance income moves fastest through rate and volume.":
    "ทบทวนเรตราคาเทียบตลาด แล้วเสนองานลูกค้าใหม่สักรายในเดือนนี้ — รายได้ฟรีแลนซ์โตเร็วที่สุดผ่านเรตและปริมาณงาน",
  "Audit your margins: raising prices 5% or cutting one recurring cost usually beats chasing new customers.":
    "ตรวจสอบมาร์จิน: ขึ้นราคา 5% หรือตัดรายจ่ายประจำหนึ่งรายการ มักได้ผลกว่าการไล่หาลูกค้าใหม่",
  "A paid internship or part-time role in your field raises income now and your starting salary later.":
    "ฝึกงานแบบมีค่าตอบแทนหรืองานพาร์ตไทม์ในสายของคุณ เพิ่มทั้งรายได้ตอนนี้และเงินเดือนเริ่มต้นในอนาคต",
  "Focus applications on roles matching your strongest skill, and treat upskilling hours as your day job.":
    "โฟกัสสมัครงานที่ตรงกับทักษะที่แข็งที่สุดของคุณ และถือว่าชั่วโมงอัปสกิลคืองานประจำ",
  "Certifications and a documented win file are the strongest levers for your next salary negotiation.":
    "ใบรับรองและแฟ้มผลงานที่บันทึกไว้คือแต้มต่อที่ดีที่สุดในการต่อรองเงินเดือนครั้งหน้า",
  "Reduce money stress": "ลดความเครียดเรื่องเงิน",
  "Write a simple monthly budget — knowing exactly where you stand improves financial well-being even before income changes.":
    "เขียนงบประมาณรายเดือนง่าย ๆ — แค่รู้สถานะการเงินชัดเจนก็ช่วยเพิ่มสุขภาวะทางการเงินได้ก่อนที่รายได้จะเปลี่ยน",
  "Move more each week": "ขยับให้มากขึ้นทุกสัปดาห์",
  "Get off the BTS/MRT one station early or walk a park loop (Benjakitti, Lumphini) — the WHO guideline is 600 MET-min/week and brisk walking counts.":
    "ลง BTS/MRT ก่อนถึงหนึ่งสถานี หรือเดินรอบสวน (เบญจกิติ ลุมพินี) — เกณฑ์ WHO คือ 600 MET-นาที/สัปดาห์ และการเดินเร็วก็นับ",
  "Brisk walks or cycling around your neighborhood count — the WHO guideline is 600 MET-min/week, about 150 minutes of moderate movement.":
    "เดินเร็วหรือปั่นจักรยานรอบละแวกบ้านก็นับ — เกณฑ์ WHO คือ 600 MET-นาที/สัปดาห์ ราว 150 นาทีของการขยับระดับปานกลาง",
  "Rebalance body composition": "ปรับสมดุลองค์ประกอบร่างกาย",
  "Composition follows the activity and nutrition components — pair regular movement with regular meals, not crash changes.":
    "องค์ประกอบร่างกายตามมาจากการขยับและโภชนาการ — จับคู่การเคลื่อนไหวสม่ำเสมอกับมื้ออาหารสม่ำเสมอ ไม่ใช่การหักโหมเปลี่ยนกะทันหัน",
  "Protect your sleep window": "ปกป้องช่วงเวลานอน",
  "Anchor a fixed wake time and go screens-off 30 minutes before bed — 7-9 hours is the target band.":
    "ตั้งเวลาตื่นให้คงที่และวางหน้าจอ 30 นาทีก่อนนอน — เป้าหมายคือ 7-9 ชั่วโมง",
  "Hit 5 portions and 2.5L": "ให้ถึงผัก 5 ส่วนและน้ำ 2.5 ลิตร",
  "Add one vegetable portion to lunch and keep a water bottle at your desk — 5 portions and 2.5L/day max this component.":
    "เพิ่มผักหนึ่งส่วนในมื้อกลางวันและวางขวดน้ำไว้ที่โต๊ะ — ผัก 5 ส่วนกับน้ำ 2.5 ลิตร/วันได้คะแนนเต็มส่วนนี้",
  "Schedule something to look forward to": "วางแผนสิ่งที่จะได้ตั้งตารอ",
  "Low WHO-5 improves with planned positive activities — book one small enjoyable thing this week and journal how it went.":
    "คะแนน WHO-5 ต่ำดีขึ้นได้ด้วยกิจกรรมเชิงบวกที่วางแผนไว้ — นัดสิ่งเล็ก ๆ ที่ชอบสักอย่างในสัปดาห์นี้ แล้วจดบันทึกว่าเป็นอย่างไร",
  "Downshift stress daily": "ผ่อนความเครียดทุกวัน",
  "Two quick nasal inhales and one long exhale (the physiological sigh) is the fastest evidence-backed stress reset — do 3 before stressful blocks.":
    "สูดจมูกสั้น ๆ สองครั้งแล้วผ่อนลมหายใจออกยาว ๆ (physiological sigh) คือวิธีรีเซ็ตความเครียดที่เร็วที่สุดตามหลักฐาน — ทำ 3 ครั้งก่อนช่วงเวลาตึงเครียด",
  "Widen your circle": "ขยายวงสัมพันธ์",
  "Message one relative and one friend you haven't spoken to this month — social networks grow with regular contact, not grand gestures.":
    "ทักญาติหนึ่งคนและเพื่อนหนึ่งคนที่เดือนนี้ยังไม่ได้คุยกัน — เครือข่ายสังคมโตจากการติดต่อสม่ำเสมอ ไม่ใช่ท่าทีอลังการ",
  "Counter loneliness with contact": "สู้ความเหงาด้วยการติดต่อ",
  "Loneliness drops fastest with voice or face time, not feeds — call one person today instead of scrolling.":
    "ความเหงาลดเร็วที่สุดด้วยเสียงหรือการเจอหน้า ไม่ใช่ฟีด — วันนี้โทรหาใครสักคนแทนการไถจอ",
  "Invest in your relationship": "ลงทุนกับความสัมพันธ์",
  "Plan one distraction-free date this week — satisfaction tracks shared, novel experiences.":
    "วางแผนเดตแบบไม่มีสิ่งรบกวนหนึ่งครั้งในสัปดาห์นี้ — ความพึงพอใจมาจากประสบการณ์ใหม่ที่ทำร่วมกัน",
  "Stack small wins": "สะสมชัยชนะเล็ก ๆ",
  "Self-efficacy grows from completed challenges — pick one finishable task each morning and log it done.":
    "ความเชื่อมั่นในความสามารถโตจากความท้าทายที่ทำสำเร็จ — เลือกงานที่จบได้หนึ่งชิ้นทุกเช้าแล้วบันทึกว่าเสร็จ",
  "Build a streak": "สร้างสตรีค",
  "Choose one skill and touch it daily for 10 minutes — consistency, not intensity, moves grit.":
    "เลือกหนึ่งทักษะแล้วฝึกทุกวันวันละ 10 นาที — ความสม่ำเสมอ ไม่ใช่ความหนักหน่วง ที่ขยับความมุ่งมั่น",
  "Block learning hours": "บล็อกเวลาเรียนรู้",
  "Put 2-3 recurring study blocks on your calendar — 5h/week maxes this component.":
    "วางช่วงเรียนซ้ำ ๆ 2-3 บล็อกในปฏิทิน — 5 ชั่วโมง/สัปดาห์ได้คะแนนเต็มส่วนนี้",
  "Give a little, regularly": "ให้ทีละน้อยแต่สม่ำเสมอ",
  "Small recurring giving beats occasional large gifts — even 100 THB/month of merit-making or charity moves this.":
    "การให้เล็ก ๆ เป็นประจำชนะการให้ก้อนใหญ่นาน ๆ ครั้ง — แค่ทำบุญหรือบริจาคเดือนละ 100 บาทก็ขยับส่วนนี้ได้",
  "Volunteer a few hours": "อาสาสักสองสามชั่วโมง",
  "4 hours a month maxes this — one weekend morning at a local temple, shelter, or community event is enough.":
    "4 ชั่วโมงต่อเดือนได้คะแนนเต็ม — เช้าวันหยุดหนึ่งครั้งที่วัด ศูนย์พักพิง หรืองานชุมชนก็พอ",
  "Practice everyday prosociality": "ฝึกน้ำใจในชีวิตประจำวัน",
  "Help one stranger or neighbor this week — directions, carrying things, a genuine check-in all count.":
    "ช่วยคนแปลกหน้าหรือเพื่อนบ้านหนึ่งคนในสัปดาห์นี้ — บอกทาง ช่วยถือของ หรือทักถามสารทุกข์ก็นับ",
  "Cut single-use plastics": "ลดพลาสติกใช้ครั้งเดียว",
  "Carry a bottle and a bag — refill stations and no-bag discounts are common around Bangkok, and the Thai average is ~3 pieces/day.":
    "พกขวดน้ำและถุงผ้า — จุดเติมน้ำและส่วนลดงดถุงมีทั่วกรุงเทพฯ ค่าเฉลี่ยคนไทยอยู่ที่ ~3 ชิ้น/วัน",
  "Carry a reusable bottle and bag on every errand — the Thai average is ~3 single-use pieces/day; beating it is very achievable.":
    "พกขวดและถุงใช้ซ้ำทุกครั้งที่ออกไปทำธุระ — ค่าเฉลี่ยคนไทย ~3 ชิ้น/วัน เอาชนะได้ไม่ยากเลย",
  "Green your commute and home": "เดินทางและอยู่บ้านแบบรักษ์โลก",
  "Swap two car trips for the BTS/MRT this week and set the aircon to 25°C or higher.":
    "เปลี่ยนการใช้รถสองเที่ยวเป็น BTS/MRT ในสัปดาห์นี้ และตั้งแอร์ 25°C ขึ้นไป",
  "Walk or cycle short errands and set the aircon to 25°C or higher — everyday habits are the whole green-behavior score.":
    "เดินหรือปั่นจักรยานทำธุระใกล้ ๆ และตั้งแอร์ 25°C ขึ้นไป — คะแนนพฤติกรรมรักษ์โลกมาจากนิสัยประจำวันล้วน ๆ",
  "Upskill for the future": "อัปสกิลเพื่ออนาคต",
  "One hour of AI/data study per week already scores — 4h/week maxes this component.":
    "เรียน AI/ข้อมูลสัปดาห์ละหนึ่งชั่วโมงก็ได้คะแนนแล้ว — 4 ชั่วโมง/สัปดาห์ได้เต็มส่วนนี้",
  "Start long-term investing": "เริ่มลงทุนระยะยาว",
  "Open an SSF/RMF or index fund with any amount — most Thai workers have no retirement savings, so starting at all puts you ahead.":
    "เปิด SSF/RMF หรือกองทุนดัชนีด้วยเงินเท่าไรก็ได้ — แรงงานไทยส่วนใหญ่ไม่มีเงินเก็บเกษียณ แค่เริ่มก็นำหน้าแล้ว",
  "Act with a longer horizon": "ลงมือโดยมองให้ไกลขึ้น",
  "Mentor someone or support one cause aimed at future generations this month.":
    "เป็นพี่เลี้ยงให้ใครสักคน หรือสนับสนุนประเด็นเพื่อคนรุ่นหลังหนึ่งเรื่องในเดือนนี้",

  // --- Onboarding input validation (Phase 1) ---
  "Enter a number.": "กรุณากรอกตัวเลข",
  "Enter a value between {min} and {max}.": "กรุณากรอกค่าระหว่าง {min} ถึง {max}",
  "Please fix the highlighted fields before continuing.":
    "กรุณาแก้ไขช่องที่ไฮไลต์ก่อนดำเนินการต่อ",

  // --- Friendlier percentiles + deep assessment (Phase 4) ---
  // NOTE: the individual in-depth questionnaire ITEM texts (PSS-10, CFC-12,
  // Rosenberg, GSE-10, Grit-12, LSNS-R, CFPB-10, RAS-7, etc.) intentionally
  // fall through to English until official Thai instrument versions are used —
  // an unofficial translation of a validated clinical scale would reduce, not
  // improve, its reliability (same reasoning as the Thai-norm decision).
  "In-depth": "เชิงลึก",
  "Measured with the full long-form instruments (deep assessment complete)":
    "วัดด้วยแบบประเมินฉบับเต็ม (ทำแบบประเมินเชิงลึกครบแล้ว)",
  "Ahead of about {pct}% of people like you": "นำหน้าผู้คนที่คล้ายคุณราว {pct}%",
  "{pct} percentile · typical range {low}–{high}": "เปอร์เซ็นไทล์ {pct} · ช่วงทั่วไป {low}–{high}",
  "in-depth verified": "ยืนยันเชิงลึกแล้ว",
  "“Percentile” = the share of people you're ahead of, so higher is better. The range shows how precise this estimate is, not a statistical confidence interval.":
    "“เปอร์เซ็นไทล์” = สัดส่วนของคนที่คุณนำหน้า ยิ่งสูงยิ่งดี ส่วนช่วงบอกว่าค่าประมาณนี้แม่นแค่ไหน ไม่ใช่ช่วงความเชื่อมั่นทางสถิติ",

  "Go deeper for more accurate scores.": "เจาะลึกเพื่อคะแนนที่แม่นยำขึ้น",
  "An optional in-depth assessment uses the full-length validated questionnaires to sharpen your estimates and tighten each percentile band.":
    "แบบประเมินเชิงลึก (ไม่บังคับ) ใช้แบบสอบถามฉบับเต็มที่ผ่านการตรวจสอบ เพื่อให้ค่าประมาณคมขึ้นและช่วงเปอร์เซ็นไทล์แคบลง",
  "In-depth sections completed: {done}/{total}": "ทำแบบประเมินเชิงลึกแล้ว: {done}/{total} หมวด",
  "Continue in-depth": "ทำเชิงลึกต่อ",
  "Start in-depth assessment": "เริ่มแบบประเมินเชิงลึก",
  "IN-DEPTH ASSESSMENT": "แบบประเมินเชิงลึก",
  "Optional • full-length validated questionnaires • one section at a time":
    "ไม่บังคับ • แบบสอบถามฉบับเต็มที่ผ่านการตรวจสอบ • ทำทีละหมวด",
  "These longer questionnaires make each aspect's estimate more reliable and tighten its percentile band. Save each section on its own — completed sections are kept as you go. Reward: +60 points per section.":
    "แบบสอบถามที่ยาวขึ้นเหล่านี้ทำให้ค่าประมาณของแต่ละด้านน่าเชื่อถือขึ้นและช่วงเปอร์เซ็นไทล์แคบลง บันทึกแต่ละหมวดแยกกันได้ — หมวดที่ทำเสร็จจะถูกเก็บไว้ รางวัล: +60 คะแนนต่อหมวด",
  "Completed — this aspect's score is verified. You can redo it to update.":
    "เสร็จแล้ว — คะแนนด้านนี้ได้รับการยืนยัน คุณทำซ้ำเพื่ออัปเดตได้",
  "Update this section": "อัปเดตหมวดนี้",
  "Save this section": "บันทึกหมวดนี้",
  "{aspect} verified in depth — score now {score} (+60 points)":
    "{aspect} ยืนยันเชิงลึกแล้ว — คะแนนตอนนี้ {score} (+60 คะแนน)",
  "In-depth assessment needs a baseline — complete the initial assessment first.":
    "แบบประเมินเชิงลึกต้องมีค่าพื้นฐานก่อน — กรุณาทำแบบประเมินเริ่มต้นให้เสร็จก่อน",

  // Percentile band labels
  "Top 10%": "10% แรก",
  "Top 25%": "25% แรก",
  "Above average": "สูงกว่าค่าเฉลี่ย",
  "Around average": "ราวค่าเฉลี่ย",
  "Below average": "ต่ำกว่าค่าเฉลี่ย",
  "Bottom 25%": "25% ล่าง",

  // Deep section titles & blurbs
  "Finance — in depth": "การเงิน — เชิงลึก",
  "Physical — in depth": "สุขภาพกาย — เชิงลึก",
  "Mental — in depth": "สุขภาพใจ — เชิงลึก",
  "Relationships — in depth": "ความสัมพันธ์ — เชิงลึก",
  "Personal Goals — in depth": "เป้าหมายส่วนตัว — เชิงลึก",
  "Social Contribution — in depth": "การมีส่วนร่วมต่อสังคม — เชิงลึก",
  "Environment — in depth": "สิ่งแวดล้อม — เชิงลึก",
  "Humanity's Future — in depth": "อนาคตของมนุษยชาติ — เชิงลึก",
  "The full 10-item CFPB Financial Well-Being Scale (onboarding used 5).":
    "แบบวัดสุขภาวะทางการเงิน CFPB ฉบับเต็ม 10 ข้อ (ตอนเริ่มต้นใช้ 5 ข้อ)",
  "Sedentary time and sleep hygiene refine your activity and sleep scores.":
    "เวลานั่งและสุขอนามัยการนอนช่วยปรับคะแนนการเคลื่อนไหวและการนอนให้แม่นขึ้น",
  "The 10-item Perceived Stress Scale adds a validated stress reading.":
    "แบบวัดความเครียด PSS-10 เพิ่มการวัดความเครียดที่ผ่านการตรวจสอบ",
  "The full LSNS-R social-network scale, plus the full relationship scale for couples.":
    "แบบวัดเครือข่ายสังคม LSNS-R ฉบับเต็ม พร้อมแบบวัดความสัมพันธ์ฉบับเต็มสำหรับผู้มีคู่",
  "Full GSE-10 and Grit-12, plus the Rosenberg Self-Esteem Scale.":
    "GSE-10 และ Grit-12 ฉบับเต็ม พร้อมแบบวัดความภาคภูมิใจในตนเองของ Rosenberg",
  "Additional giving and civic-participation habits.": "พฤติกรรมการให้และการมีส่วนร่วมพลเมืองเพิ่มเติม",
  "Additional everyday green habits.": "นิสัยรักษ์โลกในชีวิตประจำวันเพิ่มเติม",
  "The 12-item Consideration of Future Consequences scale.": "แบบวัดการคำนึงถึงผลในอนาคต (CFC) 12 ข้อ",

  // Deep instrument titles
  "CFPB Financial Well-Being Scale (full 10-item)": "แบบวัดสุขภาวะทางการเงิน CFPB (ฉบับเต็ม 10 ข้อ)",
  "Sedentary time & sleep hygiene": "เวลานั่งและสุขอนามัยการนอน",
  "Perceived Stress Scale (PSS-10, past month)": "แบบวัดความเครียด (PSS-10, เดือนที่ผ่านมา)",
  "Lubben Social Network Scale – Revised (LSNS-R)": "แบบวัดเครือข่ายสังคม Lubben ฉบับปรับปรุง (LSNS-R)",
  "Relationship Assessment Scale (full 7-item)": "แบบวัดความสัมพันธ์ (ฉบับเต็ม 7 ข้อ)",
  "General Self-Efficacy Scale (full 10-item)": "แบบวัดการรับรู้ความสามารถตนเอง (ฉบับเต็ม 10 ข้อ)",
  "Grit Scale (full 12-item)": "แบบวัดความมุ่งมั่น (ฉบับเต็ม 12 ข้อ)",
  "Rosenberg Self-Esteem Scale": "แบบวัดความภาคภูมิใจในตนเองของ Rosenberg",
  "Giving & civic habits (self-report)": "นิสัยการให้และพลเมือง (รายงานตนเอง)",
  "Everyday green habits (self-report)": "นิสัยรักษ์โลกประจำวัน (รายงานตนเอง)",
  "Consideration of Future Consequences (CFC-12)": "การคำนึงถึงผลในอนาคต (CFC-12)",

  // Deep component labels & details (aspects.js)
  "Financial well-being (CFPB-10)": "สุขภาวะทางการเงิน (CFPB-10)",
  "Perceived stress (PSS-10)": "ความเครียดที่รับรู้ (PSS-10)",
  "Social network (LSNS-R)": "เครือข่ายสังคม (LSNS-R)",
  "Relationship quality (RAS-7)": "คุณภาพความสัมพันธ์ (RAS-7)",
  "Self-efficacy (GSE-10)": "การรับรู้ความสามารถตนเอง (GSE-10)",
  "Grit (12-item)": "ความมุ่งมั่น (12 ข้อ)",
  "Self-esteem (Rosenberg)": "ความภาคภูมิใจในตนเอง (Rosenberg)",
  "Giving & civic habits": "นิสัยการให้และพลเมือง",
  "Green habits (extended)": "นิสัยรักษ์โลก (ฉบับขยาย)",
  "Future orientation (CFC-12)": "การมองการณ์ไกล (CFC-12)",
  "Full 10-item scale — raw {n}/40": "แบบเต็ม 10 ข้อ — คะแนนดิบ {n}/40",
  "Sitting time + sleep habits — raw {n}/12": "เวลานั่ง + นิสัยการนอน — คะแนนดิบ {n}/12",
  "Stress {n}/40, inverted (lower stress scores higher)": "ความเครียด {n}/40 กลับด้าน (เครียดน้อยได้คะแนนสูงกว่า)",
  "Full 12-item network scale — raw {n}/60": "แบบเครือข่ายเต็ม 12 ข้อ — คะแนนดิบ {n}/60",
  "Full 7-item scale — raw {n}/35": "แบบเต็ม 7 ข้อ — คะแนนดิบ {n}/35",
  "Full 12-item scale — raw {n}/60": "แบบเต็ม 12 ข้อ — คะแนนดิบ {n}/60",
  "Rosenberg scale — raw {n}/30": "แบบ Rosenberg — คะแนนดิบ {n}/30",
  "Additional habits — raw {n}/16": "นิสัยเพิ่มเติม — คะแนนดิบ {n}/16",
  "Scored from your full 10-item GSE — a direct match to the 25-country norm, no short-form approximation.":
    "คิดจาก GSE ฉบับเต็ม 10 ข้อของคุณ — ตรงกับเกณฑ์ 25 ประเทศพอดี ไม่ต้องประมาณจากแบบสั้น",

  // New answer-option labels used by the deep instruments
  "Almost never": "แทบไม่เคย",
  "Fairly often": "ค่อนข้างบ่อย",
  "Extremely characteristic of me": "ตรงกับฉันมากที่สุด",
  "Somewhat characteristic of me": "ค่อนข้างตรงกับฉัน",
  "Uncertain": "ไม่แน่ใจ",
  "Somewhat uncharacteristic of me": "ค่อนข้างไม่ตรงกับฉัน",
  "Extremely uncharacteristic of me": "ไม่ตรงกับฉันเลย",
  "Strongly agree": "เห็นด้วยอย่างยิ่ง",
  "Agree": "เห็นด้วย",
  "Disagree": "ไม่เห็นด้วย",
  "Strongly disagree": "ไม่เห็นด้วยอย่างยิ่ง",
  "Less than monthly": "น้อยกว่าเดือนละครั้ง",
  "Monthly": "เดือนละครั้ง",
  "A few times a month": "เดือนละไม่กี่ครั้ง",
  "Weekly": "ทุกสัปดาห์",
  "A few times a week": "สัปดาห์ละไม่กี่ครั้ง",
  "Daily": "ทุกวัน",
  "Seldom": "นาน ๆ ครั้ง",
  "None / very few": "ไม่มี / น้อยมาก",
  "A few": "ไม่กี่อย่าง",
  "Some": "บ้าง",
  "Many": "มาก",
  "Very many": "มากมาย",
  "Less than 4 hours": "น้อยกว่า 4 ชั่วโมง",
  "4–6 hours": "4–6 ชั่วโมง",
  "6–8 hours": "6–8 ชั่วโมง",
  "8–10 hours": "8–10 ชั่วโมง",
  "More than 10 hours": "มากกว่า 10 ชั่วโมง"
};
